export const translations = {
  en: {
    // Navigation
    title: "Global Scenic Live",
    home: "Home",
    list: "Scenic List",
    popular: "Popular Live",
    about: "About Us",
    search: "Search scenic spots...",
    
    // Home page
    globalDistribution: "Global Scenic Distribution",
    popularScenic: "Popular Scenic Live",
    allScenic: "All Scenic Spots",
    viewAll: "View All",
    watchNow: "Watch Now",
    live: "Live",
    back: "Back",
    
    // Detail page
    scenicIntro: "Scenic Introduction",
    highlights: "Highlights",
    weatherInfo: "Weather Information",
    todayWeather: "Today's Weather",
    currentTemp: "Current Temperature",
    suitability: "Suitability",
    suitable: "Suitable",
    uvIndex: "UV Index",
    moderate: "Moderate",
    panorama360: "360° Panoramic Experience",
    audioGuide: "Audio Guide",
    watchLive: "Watch Live",
    
    // Error messages
    browserNotSupported: "Your browser does not support the audio element.",
    
    // About page
    aboutTitle: "About Us",
    websiteIntro: "Website Introduction",
    websiteDesc1: "Global Scenic Live Platform is a website dedicated to providing real-time live streams of famous scenic spots around the world. We integrate public live streaming resources from major scenic spots globally, allowing users to enjoy natural scenery and cultural landscapes from around the world without leaving home.",
    websiteDesc2: "Our goal is to create a technology-rich tourism live streaming platform that provides users with immersive travel experiences while offering practical scenic spot information and references for travelers planning their trips.",
    techFeatures: "Technical Features",
    feature1: "Using the latest web technologies to provide smooth live streaming experience",
    feature2: "Interactive map showing global scenic spot distribution",
    feature3: "Responsive design, compatible with various devices",
    feature4: "Integrated weather, audio guide and other practical information",
    contactUs: "Contact Us",
    contactDesc: "If you have any questions or suggestions, please contact us through the following ways:",
    email: "Email: contact@sceniclive.com",
    
    // Footer
    footerText: "Page content is generated by AI, for reference only",
    
    // Weather
    sunny: "Sunny",
    cloudy: "Cloudy",
    rainy: "Rainy",
    
    // Countries/Locations
    usa: "USA",
    australia: "Australia",
    china: "China",
    
    // Scenic spots data
    scenicSpots: {
      1: {
        name: "Grand Canyon",
        location: "USA",
        address: "Arizona, USA",
        description: "World Natural Heritage, magnificent canyon landscape carved by the Colorado River",
        highlights: [
          "South Rim: Most popular viewpoint",
          "Glass Skywalk: Suspended viewing platform",
          "Colorado River Rafting: Unique experience"
        ]
      },
      2: {
        name: "Great Barrier Reef",
        location: "Australia", 
        address: "Queensland, Australia",
        description: "World's largest and longest coral reef system, one of the seven natural wonders of the world",
        highlights: [
          "Heart Reef: Most famous coral reef landscape",
          "Whitehaven Beach: One of the world's most beautiful beaches",
          "Marine Life: Rich marine ecosystem"
        ]
      },
      3: {
        name: "Mount Huangshan",
        location: "China",
        address: "Tangkou Town, Huangshan City, Anhui Province",
        description: "World Heritage site famous for its five wonders: peculiar pines, strange rocks, sea of clouds, hot springs, and winter snow",
        highlights: [
          "Welcoming Pine: Iconic landscape of Mount Huangshan",
          "Bright Summit: Second highest peak of Mount Huangshan", 
          "Flying Rock: Magical boulder landscape"
        ]
      },
      4: {
        name: "Jiuzhaigou",
        location: "China",
        address: "Aba Tibetan and Qiang Autonomous Prefecture, Sichuan Province",
        description: "Famous for six wonders: emerald lakes, layered waterfalls, colorful forests, snow peaks, Tibetan culture, and blue ice",
        highlights: [
          "Five Flower Lake: Star attraction of Jiuzhaigou, emerald water like jade",
          "Pearl Shoal Waterfall: Filming location of 1986 'Journey to the West'",
          "Mirror Lake: Dreamlike morning reflection like a sky mirror"
        ]
      },
      5: {
        name: "Forbidden City",
        location: "China", 
        address: "No.4 Jingshan Front Street, Dongcheng District, Beijing",
        description: "World's largest and best-preserved wooden ancient architectural complex",
        highlights: [
          "Hall of Supreme Harmony: Most important palace in the Forbidden City",
          "Imperial Garden: Exemplar of royal garden art",
          "Treasure Gallery: Precious cultural relics collection"
        ]
      }
    }
  },
  zh: {
    // Navigation
    title: "全球景区直播",
    home: "首页",
    list: "景区列表", 
    popular: "热门直播",
    about: "关于我们",
    search: "搜索景区...",
    
    // Home page
    globalDistribution: "全球景区分布",
    popularScenic: "热门景区直播",
    allScenic: "全部景区",
    viewAll: "查看全部",
    watchNow: "立即观看",
    live: "直播中",
    back: "返回",
    
    // Detail page
    scenicIntro: "景区介绍",
    highlights: "特色景点",
    weatherInfo: "天气信息",
    todayWeather: "今日天气",
    currentTemp: "当前温度",
    suitability: "适宜度",
    suitable: "适宜",
    uvIndex: "紫外线",
    moderate: "中等",
    panorama360: "360°全景体验",
    audioGuide: "语音导览",
    watchLive: "观看直播",
    
    // Error messages
    browserNotSupported: "您的浏览器不支持音频元素。",
    
    // About page
    aboutTitle: "关于我们",
    websiteIntro: "网站介绍",
    websiteDesc1: "全球景区直播平台是一个专注于提供世界各地著名景区实时直播的网站。我们整合了全球各大景区的公开直播资源，让用户足不出户就能欣赏到世界各地的自然风光和人文景观。",
    websiteDesc2: "我们的目标是打造一个科技感十足的旅游直播平台，为用户提供沉浸式的旅游体验，同时为计划出行的游客提供实用的景区信息和参考。",
    techFeatures: "技术特点",
    feature1: "采用最新的Web技术，提供流畅的直播体验",
    feature2: "交互式地图展示全球景区分布",
    feature3: "响应式设计，适配各种设备",
    feature4: "整合天气、语音导览等实用信息",
    contactUs: "联系我们",
    contactDesc: "如有任何问题或建议，欢迎通过以下方式联系我们：",
    email: "邮箱：contact@sceniclive.com",
    
    // Footer
    footerText: "页面内容均由 AI 生成，仅供参考",
    
    // Weather
    sunny: "晴",
    cloudy: "多云", 
    rainy: "小雨",
    
    // Countries/Locations
    usa: "美国",
    australia: "澳大利亚",
    china: "中国",
    
    // Scenic spots data
    scenicSpots: {
      1: {
        name: "美国大峡谷",
        location: "美国",
        address: "美国亚利桑那州",
        description: "世界自然遗产，科罗拉多河切割形成的壮丽峡谷景观",
        highlights: [
          "南缘：最受欢迎的观景点",
          "玻璃天空步道：悬空观景平台",
          "科罗拉多河漂流：独特体验"
        ]
      },
      2: {
        name: "澳大利亚大堡礁",
        location: "澳大利亚",
        address: "澳大利亚昆士兰州",
        description: "世界最大最长的珊瑚礁群，世界七大自然景观之一",
        highlights: [
          "心形礁：最著名的珊瑚礁景观",
          "白天堂海滩：世界最美海滩之一",
          "海洋生物：丰富的海洋生态系统"
        ]
      },
      3: {
        name: "中国黄山风景区",
        location: "中国",
        address: "安徽省黄山市汤口镇",
        description: "以奇松、怪石、云海、温泉、冬雪五绝著称的世界遗产",
        highlights: [
          "迎客松：黄山标志性景观",
          "光明顶：黄山第二高峰",
          "飞来石：神奇的巨石景观"
        ]
      },
      4: {
        name: "中国九寨沟",
        location: "中国",
        address: "四川省阿坝藏族羌族自治州",
        description: "以翠海、叠瀑、彩林、雪峰、藏情、蓝冰六绝著称",
        highlights: [
          "五花海：九寨沟C位景点，碧绿湖水犹如碧玉",
          "珍珠滩瀑布：86版《西游记》取景地",
          "镜海：清晨如天空之镜般的梦幻景象"
        ]
      },
      5: {
        name: "中国故宫博物院",
        location: "中国",
        address: "北京市东城区景山前街4号",
        description: "世界现存规模最大、保存最完整的木质结构古建筑群",
        highlights: [
          "太和殿：紫禁城最重要的宫殿",
          "御花园：皇家园林艺术典范",
          "珍宝馆：珍贵文物收藏"
        ]
      }
    }
  }
};